update faucet docs
Scaffold-Stark/ss2-docs pull request #27
Opened 2024-10-05 13:34 UTC by pheobeayo

# Add documentation for Local and Sepolia Faucets

Fixes #24 

## Types of change

- [ ] Enhancement
- [ ] Documentations with pictures references

## Comments (optional)

2024-10-05 15:41 UTC, metalboyrick requested changes
Hi @pheobeayo, really appreciate your PR! 

However I think you've misunderstood the issue, what i meant is explaining to users that we have a faucet feature that they can use in devnet to fill in their wallet in case they need any gas funds, and the sepolia faucet info that will lead them into the external starknet sepolia faucets. 

You can access the faucet on the bottom of the scaffold stark app.

Thank you!

2024-10-05 16:32 UTC, pheobeayo commented
okay , will make the changes

2024-10-06 11:39 UTC, metalboyrick requested changes
Left some comments! Don't worry you still have some time to make the changes! All the best!

2024-10-06 11:39 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +### [Starknet Foundation](https://starknet-faucet.vercel.app/)
This can be bullet points, no headers here.

2024-10-06 11:39 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +# Faucets (Available)
We can just say "Faucets"

2024-10-06 11:39 UTC, metalboyrick commented on static/img/calldata.jpg
We can delete this data if not used.

2024-10-06 11:39 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +The button is at the bottom left of the  [Demo app] (https://scaffold-stark-demo.vercel.app/debug)
This hyperlink doesn't show what you've intended I think. Can check the syntax again.

<img width="661" alt="image" src="https://github.com/user-attachments/assets/0b413575-e0cb-428d-80da-fe35c3969148">

2024-10-06 11:39 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +## Websites available for Starknet Sepolia faucets
We also need some docs on the Devnet faucet, which looks different from this sepolia window. The devnet one allows user to fill in their own wallet with some tokens

2024-10-06 11:39 UTC, metalboyrick commented on yarn.lock
Just curious how did this get updated without updating `package.json`

2024-10-06 11:41 UTC, metalboyrick requested changes

2024-10-06 11:41 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +#### In  accessing any of these websites, you will paste or input your wallet address
I think we can remove this part.

2024-10-06 11:41 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +## Websites available for Starknet Sepolia faucets
For this section, we can just say "Starknet Sepolia Faucets"

2024-10-06 23:34 UTC, Nadai2010 commented
Hi @pheobeayo great jobs, thank you, some details

- Check error in [Demo app] (https://scaffold-stark-demo.vercel.app/) vs [Demo app](https://scaffold-stark-demo.vercel.app/)
- Add the "*" that @metalboyrick mentioned, similar and consistent
![imagen](https://github.com/user-attachments/assets/7401edc0-ef76-47ee-8874-9adc21948d08)

- You must indicate in devnet that you can transfer faucet.
- 
- Better define a account address and amount as an example and 1 ETH,

```bash
curl -d '{"amount":1000000000000000000, "address":"0x064b48806902a367c8598f4f95c305e8c1a1acba5f082d294a43793113115691"}' -H "Content-Type: application/json" -X POST http://localhost:5050/mint
```

2024-10-07 02:59 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +The button is at the bottom left of the  [Demo app] (https://scaffold-stark-demo.vercel.app/debug)
@pheobeayo This is not resolved yet, you can try editing while running the localhost instance with `yarn start`. The vscode markdown doesn't necessarily give you the right representation.

2024-10-07 03:00 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +## Websites available for Starknet Sepolia faucets
@pheobeayo I meant the title could just be "Starknet Sepolia Faucets" instead of "Websites available ...."

2024-10-07 03:00 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +## Websites available for Starknet Sepolia faucets
and can remove the sub "Starknet Sepolia Faucets"

2024-10-07 03:00 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +### [Starknet Foundation](https://starknet-faucet.vercel.app/)
@pheobeayo not resolved yet

2024-10-07 03:01 UTC, metalboyrick commented on docs/deploying/deploy-faucets.mdx
> +## Websites available for Starknet Sepolia faucets
Also for the devnet, please indicate the UI path also. as shown by @Nadai2010

2024-10-07 03:01 UTC, metalboyrick commented
Hey @pheobeayo, some of the changes are still not addressed, feel free to ping us should you have any questions!

2024-10-07 03:55 UTC, pheobeayo commented
@Nadai2010, the picture was added for the Devnet local faucets. Where can I get that, please?

@metalboyrick The link in the Demo app which isn't not giving the right link is actually giving the right link with me wherever I click on it, Please what could be wrong?

2024-10-07 06:47 UTC, Nadai2010 commented
Hi @pheobeayo,  I think you can use image hat I shared , if you want to access the faucet on devnet, you should follow the [Scaffold Stark](https://github.com/Quantum3-Labs/scaffold-stark-2) repository and follow the steps to lift the UI

2024-10-07 12:15 UTC, metalboyrick commented
@pheobeayo the devnet can only be accessed if you make a local copy of the repo. you cannot use the demo link for that

2024-10-07 12:19 UTC, pheobeayo commented
Yes, I understand, I did my research too, Kindly review the changes I made on the PR @metalboyrick

2024-10-07 14:50 UTC, merged

2024-10-07 15:29 UTC, pheobeayo commented
Thank you for the support all along, it was great contributing to this! @metalboyrick  @Nadai2010