feat: add documentation for useScaffoldStrkBalance and useScaffoldEth…
Scaffold-Stark/ss2-docs pull request #28
Opened 2024-10-05 14:34 UTC by Calebux

# Task name here
feat: add documentation for useScaffoldStrkBalance and useScaffoldEth…

## Types of change

- [ ] Enhancement

2024-10-05 15:33 UTC, metalboyrick requested changes
Thanks for the PR, overall nicely done! I like how you put out the best practice guide. Just some minor comments for adjustments

2024-10-05 15:33 UTC, metalboyrick commented on docs/hooks/useScaffoldEthBalance.md
> +  address: "0xYourAddressHere",
You can use a random address here instead of a placeholder like this to make it less confusing and more real-life like.

2024-10-05 15:33 UTC, metalboyrick commented on docs/hooks/useScaffoldStrkBalance.md
> +- The hook utilizes `useDeployedContractInfo` to get contract info and `useReadContract` to read contract data.
I think we can leave out this detail.

2024-10-05 15:33 UTC, metalboyrick commented on docs/hooks/useScaffoldEthBalance.md
> +- The hook relies on useDeployedContractInfo to retrieve contract details `(address, ABI)` and useReadContract to interact with the blockchain.
I think we can leave out this detail.

2024-10-05 15:33 UTC, metalboyrick commented on docs/hooks/useScaffoldStrkBalance.md
> +  const { value, formatted, symbol } = useScaffoldStrkBalance({ address });
You can use a fake StarkNet Address here

2024-10-05 15:53 UTC, Calebux commented
Changes effected

2024-10-05 15:59 UTC, metalboyrick commented on docs/hooks/useScaffoldStrkBalance.md
> +  const { value, formatted, symbol } = useScaffoldStrkBalance({ address });
Seems you haven't address this yet, you can copy the address on the Eth side

2024-10-05 15:59 UTC, metalboyrick commented on docs/hooks/useScaffoldStrkBalance.md
> +  const { value, formatted, symbol } = useScaffoldStrkBalance({ address });
@Calebux

2024-10-05 16:00 UTC, metalboyrick commented
Fixes #26

2024-10-05 17:41 UTC, Calebux commented
Please check now

2024-10-05 17:53 UTC, Nadai2010 approved these changes

2024-10-06 11:33 UTC, metalboyrick approved these changes
Looks good!

2024-10-06 11:34 UTC, merged