Access block explorer
Scaffold-Stark/ss2-docs pull request #30
Opened 2024-10-06 17:04 UTC by Benjtalkshow

closes #25 
# Add documentation on Block Explorers

## Types of change

- [ ] Enhancement

2024-10-07 00:09 UTC, Nadai2010 commented
Hi @Benjtalkshow, Thank you for your work

**Some ideas we can use:**

- To access the explorers, we can provide a direct list:
```bash
* [Starkscan]()
* [Voyager]()
* [StarkCompas]()
``` 
- Depending on the chain in `sepolia` or `mainnet` set in the `Scaffold.config` file, it will retrieve its respective explorers for `Sepolia` or `Mainnet`. We can mention this.

- We could also include a link to the [document listing all explorers on Starknet](https://docs.starknet.io/documentation/tools/ref_block_explorers/)

2024-10-07 03:05 UTC, metalboyrick requested changes
Thanks for the hard work, kindly address @Nadai2010 's comments and you should be all good!

2024-10-07 06:06 UTC, Benjtalkshow commented
> Thanks for the hard work, kindly address @Nadai2010 's comments and you should be all good!

Alright. Thanks

2024-10-07 12:16 UTC, metalboyrick approved these changes
Let's wait for @Nadai2010 comments!

2024-10-07 12:36 UTC, Benjtalkshow commented
> Let's wait for @Nadai2010 comments!

alright ser

2024-10-08 10:22 UTC, Nadai2010 requested changes

2024-10-08 10:22 UTC, Nadai2010 commented on static/.DS_Store
No commit this file

2024-10-08 10:22 UTC, Nadai2010 commented on static/img/.DS_Store
No commit this file

2024-10-08 14:49 UTC, Benjtalkshow commented
@Nadai2010 
Made the requested chnages ser

2024-10-08 15:37 UTC, Nadai2010 requested changes

2024-10-08 15:37 UTC, Nadai2010 commented on .gitignore
Remove .gitginore

2024-10-08 16:02 UTC, Nadai2010 approved these changes

2024-10-08 16:02 UTC, merged