docs: add recipe for Read Contracts
Scaffold-Stark/ss2-docs pull request #31
Opened 2024-10-06 19:11 UTC by od-hunter

# Add recipe for Read Contract

Fixes #22 

## Types of change

- [ ] Bug
- [x] Enhancement
- [x] Documentation

2024-10-06 20:10 UTC, od-hunter commented
@metalboyrick  please review

2024-10-07 00:16 UTC, Nadai2010 commented
Hi @od-hunter, I really liked your documentation, we look forward to the changes and final review. Thanks

2024-10-07 02:53 UTC, metalboyrick requested changes
Minor changes and you're good!

2024-10-07 02:53 UTC, metalboyrick commented on docs/recipes/ReadContractDataFromNetwork.md
> +title: Read a uint from a contract
Wrong title

2024-10-07 02:53 UTC, metalboyrick commented on docs/recipes/ReadContractDataFromNetwork.md
> +By following this guide, you have successfully implemented a contract reader in your dApp that fetches and displays data from a deployed contract using the [`useScaffoldReactContract`](https://github
Typo (useScaffoldReactContract should be useScaffoldReadContract)

2024-10-07 03:05 UTC, metalboyrick requested changes

2024-10-07 03:05 UTC, metalboyrick commented on docs/recipes/ReadContractDataFromNetwork.md
Please keep the convention consistent with the other files!

2024-10-07 08:00 UTC, od-hunter commented
@metalboyrick @Nadai2010, thank you both for your review.

@metalboyrick, I wasn’t entirely clear on the 'convention consistency' feedback, but I’ve made some recent changes that I hope align with your expectations. If not, I would appreciate further clarification to ensure I implement the conventions consistently.

2024-10-07 12:11 UTC, metalboyrick commented on docs/recipes/ReadContractDataFromNetwork.md
@od-hunter I meant the file name. My bad for the unclear message.

`ReadContractDataFromNetwork.md` --> `read-contract-data.md`

(would prefer this shorter name too)

2024-10-08 10:18 UTC, Nadai2010 approved these changes

2024-10-08 10:19 UTC, merged