docs recipe #60
Scaffold-Stark/ss2-docs pull request #67
Opened 2024-12-17 10:30 UTC by suhas-sensei

# Docs recipe for "Developing on a fork“

Fixes #60 

## Types of change

- [ ] Bug
- [x] Enhancement

## Added new recipe documentation that outlines how to:
- Run and interact with a mainnet fork
- Deploy contracts to forked network
- Configure scaffold for fork network
- Test with both burner and external wallets (Argent/Braavos))

2024-12-18 05:08 UTC, metalboyrick approved these changes
looks good to me ! Thanks for the detailed explanation, will chime in @0xquantum3labs for review

2024-12-19 01:56 UTC, jrcarlos2000 requested changes

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +<summary>Here is the complete code for interacting with a forked network:</summary>
I think we dont need this section as the interaction code doesnt change with forks, and we can try to keep this file cleaner.

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +### Step 2: Create Network Interaction Component
we dont need this section the important part is forking, deploying, and connecting with the burner / extension to interact on `/debug-ui` without adding extra components.

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +### Step 3: Implement Write Functions
similarly

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +### Step 4: Add to Your App Page
similarly

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +### Step 5: Testing with Different Wallets
similarly

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +## Testing Different Wallet Types
this is good

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +### 2. Using Argent/Braavos
adding some screenshots would be helpful here, it is important to be able to connect extension wallets and send transactions, on `/debug-ui` is ok

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
> +### 2. Using Argent/Braavos
argent and braavos

2024-12-19 01:56 UTC, jrcarlos2000 commented on docs/recipes/DevelopingOnFork.md
missing in the setup to include [`mainnetFork` network](https://github.com/Scaffold-Stark/scaffold-stark-2/blob/f2df1d3f795343a03f102e42efd0ee48e8d01e29/packages/nextjs/supportedChains.ts) in `scaffold.config` otherwise it will give network error.

2024-12-19 02:32 UTC, jrcarlos2000 commented
after this is updated i will leave it to @Nadai2010 to take a look and see if this works out of the box from a fresh clone 😄

2024-12-19 08:08 UTC, suhas-sensei commented
on it ser

2024-12-19 11:11 UTC, Nadai2010 requested changes
Hi @suhas-sensei, thank you for your contributions! 

I agree with @jrcarlos2000's review. The added code can be somewhat confusing, and for the specific contract, some parameters seem to be missing. For example, the `set_greeting` method appears to lack the `amount` parameter. Additionally, it would be beneficial to add documentation clarifying the changes, such as correctly configuring the chain from `SupportedChain` using `mainnetFork` in the `scaffold.config` file. Otherwise, it can lead to network failures, even if the data retrieval is technically correct.

The screenshots below highlight the issues:
1. ![imagen](https://github.com/user-attachments/assets/4933d7c9-4126-4eea-9d00-fc4fb7fea5e3)
2. ![imagen](https://github.com/user-attachments/assets/66248f8d-d047-4dc8-a4d9-50798d620396)

Once these changes are addressed, we will review again. Thanks for your efforts and input!

2024-12-19 11:56 UTC, suhas-sensei commented
yeah, i'll look into the requested changes, thanks for the review.

2024-12-21 05:40 UTC, 0xquantum3labs commented
hello @suhas-sensei , any updates on this PR ? Thanks ! 🤝

2024-12-21 07:34 UTC, suhas-sensei commented
yes, I'm sending a pr today

2024-12-22 07:48 UTC, metalboyrick commented
gm @suhas-sensei how is it going? just wanted to remind you that the OD hack is ending soon

2024-12-22 08:45 UTC, suhas-sensei commented
yes im really sorry for the delay, sending in a couple of hours.

2024-12-22 14:30 UTC, suhas-sensei commented
Tested out the wallet connections but being honest, couldn't try testing the contract being deployed as I didn't have enough experience with Scaffold-Stark. With what I learned in the past 3 days, I worked up a recipe that ensures wallet connections work on the forked chain, as shown in the screenshots. Thank you for giving me this great learning opportunity!

2024-12-23 08:51 UTC, metalboyrick commented on docs/recipes/DevelopingOnFork.md
has this been addressed? @suhas-sensei

2024-12-23 09:02 UTC, metalboyrick requested changes

2024-12-23 11:17 UTC, suhas-sensei commented on docs/recipes/DevelopingOnFork.md
yes, updated in the scaffold.config file

2024-12-23 11:17 UTC, suhas-sensei commented on docs/recipes/DevelopingOnFork.md
> +};
sure ser

2024-12-23 18:55 UTC, suhas-sensei commented
have a look ser @metalboyrick

2024-12-23 19:03 UTC, Nadai2010 requested changes
Hi thanks for the new isFork contribution @suhas-sensei 

In point 2, I see that you add update in the scaffold.config with `const mainnetFork`, you must simply import from ‘supportedChain.ts’ this file is the one that controls that you can automate the network in [chains.maiinetFork], here is a sample 

![imagen](https://github.com/user-attachments/assets/e207eb0e-73b6-4d20-87d7-0e6667652fbc)

2024-12-23 19:10 UTC, suhas-sensei commented
ah guess im bad at refactoring, just a sec

2024-12-23 19:14 UTC, Nadai2010 commented
Thank you can also indicate that in the [.env.example](https://github.com/Scaffold-Stark/scaffold-stark-2/blob/main/packages/nextjs/.env.example] you should create a `.env` you should add the url of the devnet in this particular case, 

NEXT_PUBLIC_PROVIDER_URL=http://127.0.0.1:5050

Otherwise it will give error when connecting to rpc from the wrong network.

![Captura desde 2024-12-23 19-12-11](https://github.com/user-attachments/assets/52495dfd-e05f-491a-94b6-93e2cfb5688e)

![imagen](https://github.com/user-attachments/assets/33ba8211-05f3-40c6-83e2-784c7abf9e01)

2024-12-23 19:30 UTC, Nadai2010 approved these changes
All good for me, thank you

2024-12-24 03:02 UTC, metalboyrick approved these changes
lgtm

2024-12-24 03:05 UTC, merged