[DOCS] Productionizing Guide #56
Scaffold-Stark/ss2-docs pull request #68
Opened 2024-12-18 12:39 UTC by martinvibes

# Task name here
[DOCS] Productionizing Guide #56

Fixes #56 

## Types of change

- [] Bug
- [x] Enhancement

## Comments (optional)

2024-12-18 12:40 UTC, martinvibes commented
hey @metalboyrick kindly review :)

2024-12-19 00:16 UTC, metalboyrick requested changes
some comments, will chime in @iossocket for review too, thanks for the PR!

2024-12-19 00:16 UTC, metalboyrick commented on docs/deploying/deploy-production.mdx
> +:::tip Hint
use warning here

2024-12-19 00:16 UTC, metalboyrick commented on docs/deploying/deploy-production.mdx
> +#### 1. TypeScript and ESLint error handling:
I think need more information here, considering many beginners would want to use the framework

2024-12-19 00:16 UTC, metalboyrick commented on docs/deploying/deploy-production.mdx
> +#### 2. Webpack optimization for compatibility:
I think need more information here, considering many beginners would want to use the framework

2024-12-19 16:17 UTC, martinvibes commented
hey @metalboyrick implemented requested changes :)

2024-12-20 03:20 UTC, metalboyrick approved these changes
looks good to me but let's chime in @iossocket for review.

2024-12-20 07:50 UTC, Nadai2010 approved these changes

2024-12-22 07:49 UTC, merged

2024-12-22 07:49 UTC, metalboyrick commented
will be iterated within the team cc @Nadai2010 @iossocket